### ISSUE TITLE
pandas pin too strict

### ISSUE THREAD

**Issue by xmatthias** [emergentmethods/datasieve#20]
For a library, a dependency shouldn't be pinned with `==` - but with `>= or <=` (whatever makes sense) to avoid dependency hell.

In general, we'd want
* pinned version for CI (ideally updated automatically, for example through dependabot)
* loose version for user installs

In a normal project, this can be easily archived by `==` pinning the version in `requirements.txt` - and losely pinning the version in `setup.py`.
I've got no idea how this can be accomplished in a poetry project (otherwise this would be a PR) - but the current behavior is creating problems for projects using this (e.g. https://github.com/freqtrade/freqtrade/actions/runs/5440273501/jobs/9893040825).

**Comment by robcaulk** [comment]
Thanks for the tip, I think it is as easy as;

```
[tool.poetry.dependencies]
python = ">=3.8.1,<4.0"
scikit-learn = ">=1.1.3"
pandas = ">=2.0.3"
```
